spring.application.name=CoffeeShop

server.port=${PORT:8080}
server.address=0.0.0.0

spring.datasource.url=jdbc:${MYSQL_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect